In [1]:
import string
from collections import OrderedDict
import numpy as np
from ordered_set import OrderedSet
import pymatrix

In [2]:
small_dict = dict()

for index, letter in enumerate(string.ascii_lowercase):
       small_dict[letter] = index + 0
        
print(small_dict)

{'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4, 'f': 5, 'g': 6, 'h': 7, 'i': 8, 'j': 9, 'k': 10, 'l': 11, 'm': 12, 'n': 13, 'o': 14, 'p': 15, 'q': 16, 'r': 17, 's': 18, 't': 19, 'u': 20, 'v': 21, 'w': 22, 'x': 23, 'y': 24, 'z': 25}


In [3]:
def key_text_rule(key):
    for j in range(len(key)):
        for i in range(len(key)):
            if ((i%2==0) and (i+1!=len(key))):
                if ((key[i]) == (key[i+1])): 
                    near = i+1
                    key = key[:near] + 'x' + key[near:]
                    break

    if (len(key)%2!=0):
        key = key[:len(key)+1] + 'z'
        return key
    else:
        return key

In [4]:
plain_text = key_text_rule('welcome')
print(plain_text)

welcomez


In [5]:
n = 2
key = 'test'

In [6]:
def text_to_matrix(dict1, text, n):
    list1 = []
    for i in text:
        list1.append(dict1[i])

    matrix = np.array(list1).reshape(n,n)
    return matrix

In [7]:
key_matrix = text_to_matrix(small_dict, key, 2)
key_matrix = np.matrix(key_matrix)
key_matrix

matrix([[19,  4],
        [18, 19]])

In [8]:
main_encrypt_list = []
for i in range(len(plain_text)):
    
    plain_list1 = []
    if ((i%2==0) and (i<=len(plain_text))):
        
        plain_list1.append(small_dict[plain_text[i]])
        plain_list1.append(small_dict[plain_text[i+1]])
        
        print(plain_list1)
        
        main_encrypt_list.append((np.dot(key_matrix, np.array(plain_list1).reshape(2,))) % 26)

[22, 4]
[11, 2]
[14, 12]
[4, 25]


In [9]:
list(main_encrypt_list)

[matrix([[18,  4]]), matrix([[9, 2]]), matrix([[ 2, 12]]), matrix([[20,  1]])]

In [10]:
cipher_text = []
dict_keys=list(small_dict.keys()) 

for i in main_encrypt_list:

    val1 = i[0,0]
    val2 = i[0,1]
    
    cipher_text.append(dict_keys[val1])
    cipher_text.append(dict_keys[val2])

cipher_text = ''.join(map(str,cipher_text))
cipher_text

'sejccmub'

## Decryption

In [11]:
'''
289's multiplicative inverse is 9
'''

"\n289's multiplicative inverse is 9\n"

## invsere of a matrix

In [12]:
key_matrix

matrix([[19,  4],
        [18, 19]])

In [13]:
key_matrix_det = int(np.linalg.det(key_matrix))
key_matrix_det

289

In [14]:
def gcd(a, b):
    
    if(b == 0):
        return a
    else:
        return gcd(b, a % b)

In [15]:
def modulo_multiplicative_inverse(key_matrix_det):
    
    if (gcd(key_matrix_det,26)==1):
        
        if (key_matrix_det>27):
            key_matrix_det = key_matrix_det%26
            
        num = 1
        while((key_matrix_det * num) % 26 !=1):
            num+=1
        
        return num

    else:
        return 0 # GCD(det,26)!=1, then modulo multiplicative inverse --> Not found

In [16]:
one_by_det = modulo_multiplicative_inverse(key_matrix_det)
if one_by_det:
    print(one_by_det)
else:
    print("GCD!=1, No Modulo Multiplicative Inverse")

9


In [17]:
key_matrix

matrix([[19,  4],
        [18, 19]])

In [18]:
type(key_matrix)

numpy.matrix

In [19]:
key_matrix.tolist()

[[19, 4], [18, 19]]

In [20]:
adj = (pymatrix.matrix(key_matrix.tolist())).adjoint()
print("Adjoint of a matrix is:")
print(adj)

Adjoint of a matrix is:
 19.0  -4.0
-18.0  19.0


In [21]:
## converting into numpy and int array

key_matrix_adj = []
for i in range(n):
    key_matrix_adj.append(adj[i])
    
key_matrix_adj = np.array(key_matrix_adj).astype(int)
key_matrix_adj

array([[ 19,  -4],
       [-18,  19]])

In [22]:
## -ve numbers are removed by adding 26 to it

for i in key_matrix_adj:
    if (i[0] < 0) : i[0] += 26
    if (i[1] < 0) : i[1] += 26
    
key_matrix_adj

array([[19, 22],
       [ 8, 19]])

In [23]:
key_inverse = key_matrix_adj * one_by_det
key_inverse

array([[171, 198],
       [ 72, 171]])

In [24]:
cipher_text

'sejccmub'

In [25]:
main_decrypt_list = []
for i in range(len(cipher_text)):
    
    plain_list1 = []
    if ((i%2==0) and (i<=len(cipher_text))):
        
        plain_list1.append(small_dict[cipher_text[i]])
        plain_list1.append(small_dict[cipher_text[i+1]])
        
        main_decrypt_list.append(np.round(np.dot(key_inverse, np.array(plain_list1).reshape(2,))) % 26)
        
main_decrypt_list = np.int_(main_decrypt_list)

In [26]:
main_decrypt_list

array([[22,  4],
       [11,  2],
       [14, 12],
       [ 4, 25]])

In [27]:
original_text = []

for i in main_decrypt_list:
    dict_keys=list(small_dict.keys()) 
    original_text.append(dict_keys[i[0]])
    original_text.append(dict_keys[i[1]])

original_text = ''.join(map(str,original_text))
original_text

'welcomez'